import request from 'supertest'
import { app } from '../src/app.js'
describe('API base', () => {
  test('health responde correctamente', async () => { const response = await request(app).get('/api/v1/health'); expect(response.status).toBe(200); expect(response.body).toEqual({ success: true, data: { status: 'ok', service: 'justiturno-api' } }) })
  test('ruta inexistente devuelve formato de error', async () => { const response = await request(app).get('/api/v1/no-existe'); expect(response.status).toBe(404); expect(response.body.success).toBe(false) })
  test('auth me sin sesión devuelve 401', async () => { const response = await request(app).get('/api/v1/auth/me'); expect(response.status).toBe(401); expect(response.body.error.message).toBe('Sesión no autenticada.') })
  test('registro valida campos obligatorios', async () => { const response = await request(app).post('/api/v1/auth/register').send({}); expect(response.status).toBe(400); expect(response.body.success).toBe(false) })
  test('login valida credenciales requeridas', async () => { const response = await request(app).post('/api/v1/auth/login').send({ email: 'invalido' }); expect(response.status).toBe(400); expect(response.body.success).toBe(false) })
  test('registro, email duplicado y login real', async () => { const email = `ciudadano.prueba.${Date.now()}@ejemplo.com`; const payload = { firstName: 'Prueba', lastName: 'Ciudadana', document: String(Date.now()), phone: '3005551212', email, password: 'Prueba1234' }; const registered = await request(app).post('/api/v1/auth/register').send(payload); expect(registered.status).toBe(201); expect(registered.body.data.user.passwordHash).toBeUndefined(); const duplicate = await request(app).post('/api/v1/auth/register').send({ ...payload, document: `${payload.document}1` }); expect(duplicate.status).toBe(409); const login = await request(app).post('/api/v1/auth/login').send({ email, password: 'Prueba1234' }); expect(login.status).toBe(200); expect(login.headers['set-cookie'][0]).toContain('HttpOnly') })
  test('login rechaza contraseña incorrecta y servicios son públicos', async () => { const login = await request(app).post('/api/v1/auth/login').send({ email: 'ciudadano@demo.com', password: 'incorrecta' }); expect(login.status).toBe(401); const services = await request(app).get('/api/v1/services'); expect(services.status).toBe(200); expect(services.body.data.length).toBeGreaterThan(0) })
})
