import { useEffect, useState } from 'react'
import { ArrowLeft, CalendarDays, Clock3, MessageSquare, XCircle } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { toast } from 'sonner'
import { appointmentService } from '../../services/appointmentService'
import StatusBadge from '../../components/ui/StatusBadge'
import Modal from '../../components/ui/Modal'
import { formatDate, formatTime } from '../../utils/formatters'

export default function CitizenAppointmentDetail() {
  const { id } = useParams(); const [appointment, setAppointment] = useState(null); const [modal, setModal] = useState(false)
  useEffect(() => { appointmentService.byIdAsync(id).then(setAppointment).catch((error) => toast.error(error.message)) }, [id])
  if (!appointment) return <p className="text-sm text-slate-500">Cargando solicitud…</p>
  const cancel = async () => { try { setAppointment(await appointmentService.cancel(id)); setModal(false); toast.success('La cita fue cancelada.') } catch (error) { toast.error(error.message) } }
  const notes = Array.isArray(appointment.observations) ? appointment.observations.map((note) => note.message).join(' ') : appointment.observations
  const canCancel = ['PENDIENTE', 'ACEPTADA', 'REPROGRAMADA'].includes(appointment.status)
  return <><Link className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-primary" to="/ciudadano/citas"><ArrowLeft size={17}/>Mis citas</Link><div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section className="card p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-bold text-primary">Solicitud {appointment.code || appointment.id}</p><h1 className="mt-1 text-2xl font-bold text-navy">{appointment.service}</h1></div><StatusBadge status={appointment.status}/></div><div className="mt-7 grid gap-5 border-y py-6 sm:grid-cols-2"><div className="flex gap-3"><CalendarDays className="text-primary"/><div><p className="text-xs font-bold uppercase text-slate-500">Fecha</p><p className="mt-1 font-semibold">{formatDate(appointment.date)}</p></div></div><div className="flex gap-3"><Clock3 className="text-primary"/><div><p className="text-xs font-bold uppercase text-slate-500">Hora</p><p className="mt-1 font-semibold">{formatTime(appointment.time)}</p></div></div></div><div className="mt-6"><h2 className="font-bold text-navy">Motivo de la solicitud</h2><p className="mt-2 leading-6 text-slate-600">{appointment.reason}</p></div>{notes && <div className="mt-6 rounded-lg bg-skysoft p-4"><h2 className="flex items-center gap-2 text-sm font-bold text-navy"><MessageSquare size={17}/>Observaciones</h2><p className="mt-2 text-sm text-slate-600">{notes}</p></div>}{canCancel && <button onClick={() => setModal(true)} className="btn-secondary mt-7 border-red-200 text-red-700 hover:bg-red-50"><XCircle size={17}/>Cancelar cita</button>}</section><aside className="card h-fit p-6"><h2 className="font-bold text-navy">Seguimiento</h2><ol className="mt-6 space-y-6 border-l-2 border-blue-100 pl-5">{(appointment.history?.length ? appointment.history : [{ toStatus: appointment.status, createdAt: appointment.createdAt }]).map((entry, index) => <li className="relative text-sm" key={`${entry.id || entry.toStatus}-${index}`}><span className="absolute -left-[29px] top-1 h-3 w-3 rounded-full bg-primary ring-4 ring-white"/><strong className="block text-navy">Estado: {entry.toStatus}</strong><span className="text-slate-500">{formatDate(entry.createdAt || appointment.date)}</span></li>)}</ol></aside></div>{modal && <Modal title="¿Cancelar esta cita?" onClose={() => setModal(false)}><p className="text-sm leading-6 text-slate-600">La solicitud cambiará a estado cancelada.</p><div className="mt-6 flex justify-end gap-3"><button className="btn-ghost" onClick={() => setModal(false)}>Volver</button><button className="btn-primary bg-red-700 hover:bg-red-800" onClick={cancel}>Cancelar cita</button></div></Modal>}</>
}
