import { Routes, Route } from 'react-router-dom'
import PublicLayout from './layouts/PublicLayout'
import PortalLayout from './layouts/PortalLayout'
import ProtectedRoute from './routes/ProtectedRoute'
import HomePage from './pages/public/HomePage'
import ServicesPage from './pages/public/ServicesPage'
import ServiceDetailPage from './pages/public/ServiceDetailPage'
import NotFoundPage from './pages/public/NotFoundPage'
import LoginPage from './pages/auth/LoginPage'
import RegisterPage from './pages/auth/RegisterPage'
import CitizenDashboard from './pages/citizen/CitizenDashboard'
import NewAppointmentPage from './pages/citizen/NewAppointmentPage'
import CitizenAppointmentsPage from './pages/citizen/CitizenAppointmentsPage'
import CitizenAppointmentDetail from './pages/citizen/CitizenAppointmentDetail'
import ProfilePage from './pages/citizen/ProfilePage'
import EmployeeDashboard from './pages/employee/EmployeeDashboard'
import EmployeeAppointmentsPage from './pages/employee/EmployeeAppointmentsPage'
import EmployeeAppointmentDetail from './pages/employee/EmployeeAppointmentDetail'
import AdminDashboard from './pages/admin/AdminDashboard'
import AdminServicesPage from './pages/admin/AdminServicesPage'
import AdminSchedulesPage from './pages/admin/AdminSchedulesPage'
import AdminUsersPage from './pages/admin/AdminUsersPage'
import AdminAppointmentsPage from './pages/admin/AdminAppointmentsPage'
export default function App() { return <Routes><Route element={<PublicLayout/>}><Route path="/" element={<HomePage/>}/><Route path="/servicios" element={<ServicesPage/>}/><Route path="/servicios/:id" element={<ServiceDetailPage/>}/></Route><Route path="/login" element={<LoginPage/>}/><Route path="/registro" element={<RegisterPage/>}/><Route element={<ProtectedRoute roles={['CITIZEN']}/>}><Route element={<PortalLayout/>}><Route path="/ciudadano" element={<CitizenDashboard/>}/><Route path="/ciudadano/citas/nueva" element={<NewAppointmentPage/>}/><Route path="/ciudadano/citas" element={<CitizenAppointmentsPage/>}/><Route path="/ciudadano/citas/:id" element={<CitizenAppointmentDetail/>}/><Route path="/ciudadano/historial" element={<CitizenAppointmentsPage history/>}/><Route path="/ciudadano/perfil" element={<ProfilePage/>}/></Route></Route><Route element={<ProtectedRoute roles={['EMPLOYEE']}/>}><Route element={<PortalLayout/>}><Route path="/funcionario" element={<EmployeeDashboard/>}/><Route path="/funcionario/citas" element={<EmployeeAppointmentsPage/>}/><Route path="/funcionario/citas/:id" element={<EmployeeAppointmentDetail/>}/><Route path="/funcionario/historial" element={<EmployeeAppointmentsPage history/>}/></Route></Route><Route element={<ProtectedRoute roles={['ADMIN']}/>}><Route element={<PortalLayout/>}><Route path="/admin" element={<AdminDashboard/>}/><Route path="/admin/servicios" element={<AdminServicesPage/>}/><Route path="/admin/horarios" element={<AdminSchedulesPage/>}/><Route path="/admin/usuarios" element={<AdminUsersPage/>}/><Route path="/admin/citas" element={<AdminAppointmentsPage/>}/></Route></Route><Route path="*" element={<NotFoundPage/>}/></Routes> }
